import os

MAX_BATCH_TRANSFER_SIZE = 100
SIZEOF_FUNCTION_SELECTOR = 32
SIZEOF_ADDRESS = 40
SIZEOF_UINT256 = 64
ACCESSTOKEN_EXPIRE_TIME = 300
MAX_REWARD_AMOUNT = 2000
FROM_ADDRESS_LOC = 290
INVALID_DEPOSIT = -1
TIME_ZONE = "Asia/Taipei"

# Controllable environment variables
_DEFAULT_VALID_PAYMENT_SECONDS = 300
VALID_PAYMENT_SECONDS = os.environ.get('VALID_PAYMENT_SECONDS', _DEFAULT_VALID_PAYMENT_SECONDS)

_DEFAULT_DEBUG_MODE = False
DEBUG_MODE = os.environ.get('DEBUG_MODE', _DEFAULT_DEBUG_MODE)